projects:
  flow:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: vsjugt6qn5dxzgu5dam6httswe
      endpoints:
        prod: >-
          https://dojrsfx4k5gvvdxsabltgstcue.appsync-api.us-east-1.amazonaws.com/graphql
