// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "123.flowchoice.net",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://123.flowchoice.net.s3-website-us-east-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://gumxwz3jwvfolb72q3psl747qu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mcw2yfvvtnaipfuwnqivs4ta7i"
};


export default awsmobile;
